version: "3"
services: 
    app:
        build: ./app/
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./app:/go/src/app
        depends_on: 
            - mysql
            
    mysql:
        build: ./mysql/
        volumes:
            - ./mysql/init:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=golang
            # -  TZ=Asia/Tokyo
        ports:
            - "3306:3306"
        container_name: mysql-container