version: "3" # composeファイルのバージョン
services: 
    app: # サービス名
        build: . # ビルドに使うDockerfileの場所
        tty: true # コンテナの永続化
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8080:8080"
        volumes:
            - ./app:/go/src/app # マウントディレクトリ
        depends_on: 
            - mysql

    mysql:
        build: ./mysql/
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
        environment: 
            - MYSQL_ROOT_PASSWORD=golang
        ports:
            - "3306:3306"